language: node_js
os: linux
dist: bionic
node_js:
  - lts/*
before_script:
  - yarn run build
jobs:
  include:
    - stage: deploy
      name: "Deploy Demo"
      deploy:
        provider: pages
        local_dir: dist
        token: $Github_Token
        fqdn: vue-demo.mrhope.site
        cleanup: false
        strategy: git
        project_name: vue-demo
        committer_from_gh: true
        edge: true

stages:
  - name: deploy
    if: branch = master
