language: node_js
os: linux
dist: bionic
node_js:
  - lts/*
jobs:
  include:
    # 测试构建项目
    - stage: test-build
      name: "Test Build Process"
      script: yarn run build

    # 部署
    - stage: deploy
      name: "Deploy Demo"
      script: yarn run build
      deploy:
        provider: pages
        local_dir: dist
        token: $Github_Token
        fqdn: vue-demo.mrhope.site
        cleanup: false
        strategy: git
        project_name: vue-demo
        committer_from_gh: true
        edge: true

stages:
  - name: test-build
    if: branch != master
  - name: deploy
    if: branch = master
